# Credit Risk Resampling Techniques

In [16]:
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [5]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [56]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

In [57]:
df.head()

loan_amnt  int_rate  installment home_ownership  annual_inc  \
0    10500.0    0.1719       375.35           RENT     66000.0   
1    25000.0    0.2000       929.09       MORTGAGE    105000.0   
2    20000.0    0.2000       529.88       MORTGAGE     56000.0   
3    10000.0    0.1640       353.55           RENT     92000.0   
4    22000.0    0.1474       520.39       MORTGAGE     52000.0   

  verification_status   issue_d loan_status pymnt_plan    dti  delinq_2yrs  \
0     Source Verified  Mar-2019    low_risk          n  27.24          0.0   
1            Verified  Mar-2019    low_risk          n  20.23          0.0   
2            Verified  Mar-2019    low_risk          n  24.26          0.0   
3            Verified  Mar-2019    low_risk          n  31.44          0.0   
4        Not Verified  Mar-2019    low_risk          n  18.76          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  total_acc  \
0             0.0       8.0      0.0     1609.0       14.0   
1             0.0      17.0      1.0    18368.0       34.0   
2             0.0       8.0      0.0    13247.0       21.0   
3             1.0      10.0      1.0    17996.0       23.0   
4             1.0      14.0      0.0     9091.0       28.0   

  initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  \
0                   w   10204.87       10204.87       355.29           355.29   
1                   w   24293.13       24293.13       873.53           873.53   
2                   w   19636.79       19636.79       485.44           485.44   
3                   w    9719.34        9719.34       335.33           335.33   
4                   w   21614.73       21614.73       484.36           484.36   

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0           295.13          60.16                 0.0         0.0   
1           706.87         166.66                 0.0         0.0   
2           363.21         122.23                 0.0         0.0   
3           280.66          54.67                 0.0         0.0   
4           385.27          99.09                 0.0         0.0   

   collection_recovery_fee  last_pymnt_amnt next_pymnt_d  \
0                      0.0           375.35     May-2019   
1                      0.0           929.09     May-2019   
2                      0.0           529.88     May-2019   
3                      0.0           353.55     May-2019   
4                      0.0           520.39     May-2019   

   collections_12_mths_ex_med  policy_code application_type  acc_now_delinq  \
0                         0.0          1.0       Individual             0.0   
1                         0.0          1.0       Individual             0.0   
2                         0.0          1.0       Individual             0.0   
3                         0.0          1.0       Individual             0.0   
4                         0.0          1.0       Individual             0.0   

   tot_coll_amt  tot_cur_bal  open_acc_6m  open_act_il  open_il_12m  \
0         178.0      38199.0          3.0          4.0          2.0   
1         165.0     228119.0          3.0          3.0          2.0   
2           0.0      45684.0          2.0          3.0          2.0   
3           0.0      68784.0          0.0          4.0          1.0   
4           0.0     177745.0          0.0          1.0          0.0   

   open_il_24m  mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  \
0          4.0                 3.0       36590.0     59.0          1.0   
1          3.0                 4.0       42273.0     86.0          4.0   
2          3.0                 4.0       32437.0     75.0          2.0   
3          3.0                 9.0       50788.0     66.0          0.0   
4          2.0                14.0       16828.0     84.0          1.0   

   open_rv_24m  max_bal_bc  all_util  total_rev_hi_lim  inq_fi  total_cu_tl  \
0          2.0      1553.0      58.0            3700.0     1.0          0.0

In [58]:
df = pd.get_dummies(df, columns=['initial_list_status',
                                   'home_ownership',
                                   'application_type',
                                   'verification_status',
                                   'issue_d',
                                   'next_pymnt_d',
                                   'pymnt_plan', 
                                   'hardship_flag', 
                                   'debt_settlement_flag'], drop_first=True)

In [59]:
df['loan_status'] = np.where(df['loan_status'] == 'low_risk', 0, 1)

In [60]:
df['loan_status'].value_counts()

0    68470
1      347
Name: loan_status, dtype: int64

# Split the Data into Training and Testing

In [61]:
# Create our features
X = df.drop('loan_status', axis=1)


# Create our target
y = df['loan_status']

In [62]:
# Check the balance of our target values
y.value_counts()

0    68470
1      347
Name: loan_status, dtype: int64

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
    y, random_state=1, stratify=y)

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [64]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [67]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)
y_pred = model.predict(X_test)

In [68]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.5902689647114754

In [70]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[9977, 7141],
       [  35,   52]], dtype=int64)

In [71]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.58      0.60      0.74      0.59      0.35     17118
          1       0.01      0.60      0.58      0.01      0.59      0.35        87

avg / total       0.99      0.58      0.60      0.73      0.59      0.35     17205



### SMOTE Oversampling

In [73]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1,
sampling_strategy='auto').fit_resample(
   X_train, y_train)

In [74]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

y_pred = model.predict(X_test)

In [75]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.6172721998622139

In [76]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[11295,  5823],
       [   37,    50]], dtype=int64)

In [77]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.66      0.57      0.79      0.62      0.38     17118
          1       0.01      0.57      0.66      0.02      0.62      0.38        87

avg / total       0.99      0.66      0.58      0.79      0.62      0.38     17205



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [97]:
# Resample the data using the ClusterCentroids resampler
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

In [98]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

y_pred = model.predict(X_test)

In [99]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.5007272038709002

In [100]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[8092, 9026],
       [  41,   46]], dtype=int64)

In [101]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.47      0.53      0.64      0.50      0.25     17118
          1       0.01      0.53      0.47      0.01      0.50      0.25        87

avg / total       0.99      0.47      0.53      0.64      0.50      0.25     17205



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [92]:
# Resample the training data with SMOTEENN
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)

In [93]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [94]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.6097231790694208

In [95]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[9856, 7262],
       [  31,   56]], dtype=int64)

In [96]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.58      0.64      0.73      0.61      0.37     17118
          1       0.01      0.64      0.58      0.02      0.61      0.37        87

avg / total       0.99      0.58      0.64      0.73      0.61      0.37     17205

